FROM registry.centos.org/sclo/postgresql-95-centos7:latest
MAINTAINER Slavek Kabrda <slavek@redhat.com>

USER 0

RUN yum install -y epel-release && yum install -y python-pip python-alembic python-psycopg2 python-zmq python-devel gcc libffi-devel openssl-devel

COPY files/run-postgresql /usr/bin/
COPY files/postgres-post-init /usr/bin/

USER 26

COPY ./anitya/ /src
RUN pip install --user -r /src/requirements.txt
