FROM registry.centos.org/centos/centos:7
MAINTAINER Slavek Kabrda <slavek@redhat.com>

USER 0

RUN yum install -y epel-release && yum install -y python-pip python-alembic python-psycopg2 python-zmq python-devel gcc libffi-devel openssl-devel postgresql

COPY ./anitya/ /src
COPY ./files/rundbmigrations.sh ./files/anitya-env.sh /src/

RUN pip install -r /src/requirements.txt

RUN chown -R 26 /src

USER 26

WORKDIR /src

CMD /src/rundbmigrations.sh
RUN ls -la /src
