FROM slavek/anitya-server

RUN dnf install -y cronie

COPY files/anitya.crontab /etc/cron.d/
RUN chmod 0644 /etc/cron.d/anitya.crontab
COPY files/runcronjobincontainer.sh /src
RUN touch /var/tmp/anitya_cron.log
RUN touch /var/tmp/anitya_cronscript.log

ENTRYPOINT env > /env.sh && crond -s && tail -f /var/tmp/anitya_cron.log /var/tmp/anitya_cronscript.log
