FROM fedora

RUN dnf install -y gcc python-psycopg2 python-devel libffi-devel openssl-devel gcc-c++ redhat-rpm-config rpm-python httpd httpd-devel && \
    dnf autoremove -y && \
    dnf clean all -y

COPY ./anitya/ /src
COPY ./files/runincontainer.sh /src
COPY ./files/anitya.wsgi /src
COPY ./files/anitya-env.sh /src
WORKDIR /src

RUN pip install -r requirements.txt mod_wsgi
EXPOSE 5000
ENTRYPOINT /src/runincontainer.sh
