#!/bin/bash

export ANITYA_DB_URL="postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@${ANITYA_POSTGRES_SERVICE_HOST}:${ANITYA_POSTGRES_SERVICE_PORT}/${POSTGRESQL_DATABASE}"
echo "DB_URL = '${ANITYA_DB_URL}'" > /src/config.py
