apiVersion: v1
kind: Template

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: bayesian-anitya
    name: bayesian-anitya
  spec:
    replicas: 1
    selector:
      service: bayesian-anitya
    template:
      metadata:
        labels:
          service: bayesian-anitya
      spec:
        containers:
        - env:
          - name: ANITYA_POSTGRES_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: host
          - name: ANITYA_POSTGRES_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: port
          - name: POSTGRESQL_INITIAL_DATABASE
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: initial-database
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: username
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: bayesian-anitya
          ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/version
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 6
          livenessProbe:
            httpGet:
              path: /api/projects/names
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 6
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.expose: "true"
    labels:
      service: bayesian-anitya
    name: bayesian-anitya
  spec:
    ports:
    - name: "5000"
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      service: bayesian-anitya

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: bayesian-anitya-update-job
    name: bayesian-anitya-update-job
  spec:
    replicas: 1
    selector:
      service: bayesian-anitya-update-job
    template:
      metadata:
        labels:
          service: bayesian-anitya-update-job
      spec:
        containers:
        - env:
          - name: ANITYA_POSTGRES_SERVICE_HOST
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: host
          - name: ANITYA_POSTGRES_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: port
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: database
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: password
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: anitya-postgres
                key: username
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: bayesian-anitya-update-job
          command:
            - /src/runupdatejob.sh
          resources:
            limits:
              memory: "512Mi"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "slavek/anitya-server"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag
